// Generated by CoffeeScript 1.8.0
chrome.browserAction.onClicked.addListener(function(tab) {
  console.log('Turning ' + tab.url + ' red!');
  return chrome.tabs.executeScript({
    code: 'document.body.style.backgroundColor="red"'
  });
});
