// Generated by CoffeeScript 1.9.2
chrome.browserAction.onClicked.addListener(function(tab) {
  console.log('Turning ' + tab.url + ' red!');
  chrome.tabs.insertCSS({
    file: "styles/main.css"
  }, function() {});
  return chrome.tabs.executeScript({
    file: "scripts/jquery.min.js"
  }, function() {
    return chrome.tabs.executeScript({
      file: "scripts/react.js"
    }, function() {
      return chrome.tabs.executeScript({
        file: 'scripts/submit_text.js'
      });
    });
  });
});
